server:
  port: 8087

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/CorsoAcademy
    password: academy
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
